var canvas = null,
    ctx = null,
    images = [],
    speed = 20,
    dy1 = 0,
    dy2 = 500,
    dy3 = 1000,
    games = 5,
    gameStop = false,
    ticket = [],
    prize = -1,
    stop = [false, false, false, false, false],
    play = true,
    loopID = null,
    premii = ["Cafea",
              "Origami",
              "Bratara",
              "Sticker",
              "Carte"];